const dotenv = require("dotenv");
dotenv.config();

module.exports = {
  DISCORD_TOKEN: process.env.DISCORD_TOKEN,
  DISCORD_CLIENT_ID: process.env.DISCORD_CLIENT_ID,
  DISCORD_CLIENT_SECRET: process.env.DISCORD_CLIENT_SECRET,
  DISCORD_GUILD_ID: process.env.DISCORD_GUILD_ID,

  BRAPI_API_KEY: process.env.BRAPI_API_KEY,

  BRANDFETCH_API_KEY: process.env.BRANDFETCH_API_KEY,
  LOGODEV_PUBLISHABLE_API_KEY: process.env.LOGODEV_PUBLISHABLE_API_KEY,
  LOGO_DEV_SECRET_API_KEY: process.env.LOGO_DEV_SECRET_API_KEY,
};
